# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Xilinx/local_PR_test_01/local_PR_test_01.srcs/constraints.xdc

# IP: D:/Xilinx/local_PR_test_01/local_PR_test_01.srcs/sem_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sem_0 || ORIG_REF_NAME==sem_0} -quiet] -quiet

# Block Designs: D:/Xilinx/local_PR_test_01/local_PR_test_01.srcs/mb_pr_01/mb_pr_01.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_pr_01 || ORIG_REF_NAME==mb_pr_01} -quiet] -quiet

# IP: D:/Xilinx/local_PR_test_01/local_PR_test_01.srcs/mb_pr_01/ip/mb_pr_01_axi_hwicap_0_0/mb_pr_01_axi_hwicap_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_pr_01_axi_hwicap_0_0 || ORIG_REF_NAME==mb_pr_01_axi_hwicap_0_0} -quiet] -quiet

# IP: D:/Xilinx/local_PR_test_01/local_PR_test_01.srcs/mb_pr_01/ip/mb_pr_01_microblaze_0_0/mb_pr_01_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_pr_01_microblaze_0_0 || ORIG_REF_NAME==mb_pr_01_microblaze_0_0} -quiet] -quiet

# IP: D:/Xilinx/local_PR_test_01/local_PR_test_01.srcs/mb_pr_01/ip/mb_pr_01_axi_uartlite_0_0/mb_pr_01_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_pr_01_axi_uartlite_0_0 || ORIG_REF_NAME==mb_pr_01_axi_uartlite_0_0} -quiet] -quiet

# IP: D:/Xilinx/local_PR_test_01/local_PR_test_01.srcs/mb_pr_01/ip/mb_pr_01_mdm_0_0/mb_pr_01_mdm_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_pr_01_mdm_0_0 || ORIG_REF_NAME==mb_pr_01_mdm_0_0} -quiet] -quiet

# IP: D:/Xilinx/local_PR_test_01/local_PR_test_01.srcs/mb_pr_01/ip/mb_pr_01_dlmb_v10_0/mb_pr_01_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_pr_01_dlmb_v10_0 || ORIG_REF_NAME==mb_pr_01_dlmb_v10_0} -quiet] -quiet

# IP: D:/Xilinx/local_PR_test_01/local_PR_test_01.srcs/mb_pr_01/ip/mb_pr_01_ilmb_v10_0/mb_pr_01_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_pr_01_ilmb_v10_0 || ORIG_REF_NAME==mb_pr_01_ilmb_v10_0} -quiet] -quiet

# IP: D:/Xilinx/local_PR_test_01/local_PR_test_01.srcs/mb_pr_01/ip/mb_pr_01_dlmb_bram_if_cntlr_0/mb_pr_01_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_pr_01_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_pr_01_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: D:/Xilinx/local_PR_test_01/local_PR_test_01.srcs/mb_pr_01/ip/mb_pr_01_ilmb_bram_if_cntlr_0/mb_pr_01_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_pr_01_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_pr_01_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: D:/Xilinx/local_PR_test_01/local_PR_test_01.srcs/mb_pr_01/ip/mb_pr_01_lmb_bram_0/mb_pr_01_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_pr_01_lmb_bram_0 || ORIG_REF_NAME==mb_pr_01_lmb_bram_0} -quiet] -quiet

# IP: D:/Xilinx/local_PR_test_01/local_PR_test_01.srcs/mb_pr_01/ip/mb_pr_01_rst_clk_wiz_1_100M_0/mb_pr_01_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_pr_01_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mb_pr_01_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: D:/Xilinx/local_PR_test_01/local_PR_test_01.srcs/mb_pr_01/ip/mb_pr_01_xbar_0/mb_pr_01_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_pr_01_xbar_0 || ORIG_REF_NAME==mb_pr_01_xbar_0} -quiet] -quiet

# IP: D:/Xilinx/local_PR_test_01/local_PR_test_01.srcs/mb_pr_01/ip/mb_pr_01_microblaze_0_axi_periph_0/mb_pr_01_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_pr_01_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mb_pr_01_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: D:/Xilinx/local_PR_test_01/local_PR_test_01.srcs/mb_pr_01/ip/mb_pr_01_axi_quad_spi_0_0/mb_pr_01_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_pr_01_axi_quad_spi_0_0 || ORIG_REF_NAME==mb_pr_01_axi_quad_spi_0_0} -quiet] -quiet

# IP: D:/Xilinx/local_PR_test_01/local_PR_test_01.srcs/mb_pr_01/ip/mb_pr_01_axi_gpio_0_0/mb_pr_01_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_pr_01_axi_gpio_0_0 || ORIG_REF_NAME==mb_pr_01_axi_gpio_0_0} -quiet] -quiet

# IP: D:/Xilinx/local_PR_test_01/local_PR_test_01.srcs/mb_pr_01/ip/mb_pr_01_axi_gpio_1_0/mb_pr_01_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_pr_01_axi_gpio_1_0 || ORIG_REF_NAME==mb_pr_01_axi_gpio_1_0} -quiet] -quiet

# XDC: d:/local_PR_test_01.gen/sources_1/bd/mb_pr_01/mb_pr_01_ooc.xdc
