# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Xilinx/local_PR_test_01/local_PR_test_01.srcs/mb_pr_01/ip/mb_pr_01_axi_hwicap_0_0/mb_pr_01_axi_hwicap_0_0.xci
# IP: The module: 'mb_pr_01_axi_hwicap_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/local_PR_test_01.gen/sources_1/bd/mb_pr_01/ip/mb_pr_01_axi_hwicap_0_0/mb_pr_01_axi_hwicap_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_pr_01_axi_hwicap_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/local_PR_test_01.gen/sources_1/bd/mb_pr_01/ip/mb_pr_01_axi_hwicap_0_0/mb_pr_01_axi_hwicap_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_pr_01_axi_hwicap_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/local_PR_test_01.gen/sources_1/bd/mb_pr_01/ip/mb_pr_01_axi_hwicap_0_0/mb_pr_01_axi_hwicap_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_pr_01_axi_hwicap_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/Xilinx/local_PR_test_01/local_PR_test_01.srcs/mb_pr_01/ip/mb_pr_01_axi_hwicap_0_0/mb_pr_01_axi_hwicap_0_0.xci
# IP: The module: 'mb_pr_01_axi_hwicap_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/local_PR_test_01.gen/sources_1/bd/mb_pr_01/ip/mb_pr_01_axi_hwicap_0_0/mb_pr_01_axi_hwicap_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_pr_01_axi_hwicap_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/local_PR_test_01.gen/sources_1/bd/mb_pr_01/ip/mb_pr_01_axi_hwicap_0_0/mb_pr_01_axi_hwicap_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_pr_01_axi_hwicap_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/local_PR_test_01.gen/sources_1/bd/mb_pr_01/ip/mb_pr_01_axi_hwicap_0_0/mb_pr_01_axi_hwicap_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_pr_01_axi_hwicap_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
